[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[rpc_endpoints]
local =  "http://127.0.0.1:8545"
sepolia = "https://rpc.sepolia.org"

[etherscan]
sepolia = {key ="2FWT92RJP986P431NUK4XVX9NWQNY5PVIQ"}

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options